server:
  port: 8888
spring:
  application:
    name: config-client
  cloud:
    config:
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig/
          search-paths: repo
          password:
          username:
      label: master

